### ISSUE TITLE
Why TEI elements are removed in the output file?

### ISSUE THREAD

**Issue by arojascastro** [hdcaicyt/Recogito-TEI#11]
If the input file is https://github.com/hdcaicyt/Recogito-TEI/blob/master/Ruy_Diaz-La_Argentina_Manuscrita-proposal.tei.xml and the output file from Recogito is https://github.com/hdcaicyt/Recogito-TEI/blob/master/Ruy_Diaz-La_Argentina_Manuscrita-sample.tei.xml, I am wondering why in the output file there are some structural TEI elements missing.

For instance:

### input

```xml
<head>La Argentina</head>
      <div>
<p>Dedicatoria</p>
```

### output

```xml
 <body><div><p>La Argentina


Dedicatoria

A don 
```

I think the output should contain exactly the same elements - plus the TEI elements added using Recogito, that is, `persName`, `placeName` etc. in addition to the list of relationships. 

If this is not possible (for any  reason), then it should be stated which TEI elements are supported in the input process. Encoding a text is sometimes time-consuming so no one should lose their work.

**Comment by GusRiva** [comment]
I think the proposal is not the input, it's a suggestion of how the output should look like. At least that is what I understood.

**Comment by arojascastro** [comment]
Yes, you are right @GusRiva !
