### ISSUE TITLE
Import and Export TEI files

### ISSUE THREAD

**Issue by arojascastro** [hdcaicyt/Recogito-TEI#18]
I would like to open this issue to discuss an alternative scenario. I understand that to the moment we have focused on TEI problems caused when a user imports a TXT. However, it is also possible that a person has already a TEI XML file with basic structural information and would like to enrich the text with annotation of places and people. For this reason, I uploaded several of my TEI files to Recogito and I found out three things:

- metadata from TEI is not recovered in Recogito Settings:

![Captura de pantalla 2019-08-15 a las 11 13 21](https://user-images.githubusercontent.com/7340111/63085782-a3ebba80-bf4e-11e9-80ea-3be4094412d6.png)

On the other hand, I do not know to what extent this is important, because the metadata is still in the TEI file and it is displayed in the author/editor mode.

- users can select which NER software they want to use depending on the language (that is good, it is always great to support multilingualism)

- at the moment, the export is not working and I cannot see how the entities are represented but I guess it follows the same method as discussed in TXT files:

![Captura de pantalla 2019-08-15 a las 11 15 52-crop](https://user-images.githubusercontent.com/7340111/63086090-663b6180-bf4f-11e9-8370-e77e5c6f63da.png)

There are other export options that are currently working (CSV).

**Comment by rsimon** [comment]
+1 on picking up (a defined set?) of metadata properties from the header. I might be able to fit that into the work plan, later this year. But can't guarantee for sure.

Regarding the error, @arojascastro: looks like the export is not a general bug (I tested just now and it worked for several TEIs I tried). It must be a bug encountered specifically for the TEI file you are using. Can you post (or E-Mail) me the link to the document in Recogito?

**Comment by arojascastro** [comment]
Thanks! None of my texts can be downloaded:
- https://recogito.pelagios.org/document/xjwvd64osa8cyg
- https://recogito.pelagios.org/document/ehsk2gxgmahwl8

**Comment by rsimon** [comment]
The Nullpointer error is fixed (https://github.com/pelagios/recogito2/commit/854fce129ea6e8c58dbf7d8c8c1e6ae980602e6a) - and it was a powerful reminder I really (really!) need to follow @hcayless advice https://github.com/pelagios/recogito2/issues/634 ;-)

**Comment by rsimon** [comment]
Ah, wait - not quite. Another fix coming ;-)
