### ISSUE TITLE
Imprint metadata

### ISSUE THREAD

**Issue by rsimon** [hdcaicyt/Recogito-TEI#7]
We don't record this information in Recogito. I'd be slightly reluctant to add more metadata fields to Recogito. It's deliberately supposed not t be a metadata management tool. IMO more specific data such as this could be added afterwards, outside of Recogito. Alternatively, when uploading the source file as TEI, this data would be retained from the original, anyway.

https://github.com/hdcaicyt/Recogito-TEI/blob/b3f8ef18a615b79ac164ce10cb4b9292fe16a318/Ruy_Diaz-La_Argentina_Manuscrita-proposal.tei.xml#L25

**Comment by arojascastro** [comment]
In that case, I think the user should know which elements are supported as input. Then work with Recogito to annotate entities, export and keep encoding other metadata or structural elements. At the moment, I see a problem if the user encodes certain things and then after working with Recogito s/he  gains information about entities but loses information on other aspects after exporting.

**Comment by susannalles** [comment]
I also think that the user in Recogito should know which fields / TEI tags are available for input and export.

**Comment by rsimon** [comment]
Just to clarify/summarize what's available & implemented right now:

- When __exporting a .txt file__ as TEI, a select set of metadata fields are converted to header tags - I agree we should document this somewhere.
- When __exporting a .tei.xml__ (i.e. originally uploaded as TEI) as TEI, Recogito makes __no change__ to whatever was in the original TEI header fields. Exporting the file will return the original header as it was
- When __importing__ a .tei.xml file, Recogito will __not__ parse the original header, nor pick that information up for the internal metadata (title, author, etc.) It potentially _could_ do that (with a bit of extra development), and merge changes made in the Recogito UI back into the original TEI.

**Comment by arojascastro** [comment]
Sorry! I had misunderstood this - thank you for the clarification @rsimon and sorry again.
