### ISSUE TITLE
Element note target

### ISSUE THREAD

**Issue by GusRiva** [hdcaicyt/Recogito-TEI#9]
`<note>`  elements are outside the elements they refer to, usually as following-sibling. However, it might be useful to add a `@target` attribute pointing to the corresponding xml:id to make it easier to identify the reference.

**Comment by susannalles** [comment]
It could also be encoded inside the element maybe.

**Comment by arojascastro** [comment]
@rsimon  says that he could add a `@target` pointing to `note`.

**Comment by rsimon** [comment]
Implemented in the codebase & will go live with the next server update.

**Comment by GusRiva** [comment]
I tested it and seems to be working ok. Should we close the issue?

**Comment by rsimon** [comment]
Great, thanks! Closing :-)

**Comment by rsimon** [comment]
I think we can close this issue? If there's someone with sufficient permissions to close, please feel free :-)

**Comment by arojascastro** [comment]
I have no permission to close this issue. Can anyone else try?
